<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>btn_search_k</name>
   <tag></tag>
   <elementGuidId>5ea8915d-7a71-435f-a6e1-f2283c06792f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//div[@class='VlcLAe']//input[@name='btnK']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//div[@class='VlcLAe']//input[@name='btnK']</value>
   </webElementProperties>
</WebElementEntity>
